# Generated by Django 5.0.2 on 2024-04-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=50)),
                ('diag_group', models.CharField(max_length=50)),
                ('arrive_name', models.CharField(max_length=50)),
                ('set_date', models.DateField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
